{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "certheim.serviceAccountName" . }}
  labels:
    {{- include "certheim.labels" . | nindent 4 }}
{{- end -}}
