#!/usr/bin/env bash
# release.sh - compute the next semantic version from Conventional Commits since
# the last v* tag, and (if a release is warranted) update VERSION + CHANGELOG.md
# (committed) and write a TRANSIENT RELEASE-NOTES-vX.Y.Z.md. The CALLER (the CI
# `release` job) commits VERSION + CHANGELOG.md, tags, pushes, and uses the notes
# file ONLY to populate the GitLab Release page - it is gitignored and never
# committed (CHANGELOG.md is the durable in-tree history).
#
# Bump rules (https://www.conventionalcommits.org + SemVer):
#   * a commit with `<type>!:` OR a `BREAKING CHANGE` body  -> MAJOR (x.0.0)
#   * any `feat:` / `feat(scope):`                          -> MINOR (2.x.0)  <-- new feature
#   * any `fix|perf|refactor|build|revert`                  -> PATCH (2.1.x)  <-- patch
#   * nothing release-worthy (only docs/chore/ci/test/...)  -> no release
# A manually-set VERSION higher than the last tag is honored (force a version).
#
# Output (stdout): the new version "X.Y.Z", or "none" if there's nothing to cut.
# Idempotent: prints "none" (writes nothing) if the target tag already exists or
# the target is already a section in CHANGELOG.md.
set -euo pipefail
cd "$(dirname "$0")/.."

last_tag="$(git describe --tags --match 'v[0-9]*' --abbrev=0 2>/dev/null || true)"
if [ -z "$last_tag" ]; then last_tag="v0.0.0"; range="HEAD"; else range="${last_tag}..HEAD"; fi
lv="${last_tag#v}"; IFS=. read -r LMAJ LMIN LPAT <<<"$lv"
LMAJ="${LMAJ:-0}"; LMIN="${LMIN:-0}"; LPAT="${LPAT:-0}"

subjects="$(git log --no-merges --pretty='%s' "$range" 2>/dev/null || true)"
bodies="$(git log --no-merges --pretty='%B'  "$range" 2>/dev/null || true)"

bump=""
if printf '%s\n' "$bodies" | grep -qE 'BREAKING CHANGE' \
   || printf '%s\n' "$subjects" | grep -qE '^[a-z]+(\([^)]+\))?!:'; then
  bump=major
elif printf '%s\n' "$subjects" | grep -qE '^feat(\([^)]+\))?:'; then
  bump=minor
elif printf '%s\n' "$subjects" | grep -qE '^(fix|perf|refactor|build|revert)(\([^)]+\))?:'; then
  bump=patch
fi

case "$bump" in
  major) target="$((LMAJ+1)).0.0" ;;
  minor) target="${LMAJ}.$((LMIN+1)).0" ;;
  patch) target="${LMAJ}.${LMIN}.$((LPAT+1))" ;;
  *)     echo "none"; exit 0 ;;
esac

# Honor a manually-set higher VERSION (lets a maintainer force a target).
cur="$(cat VERSION 2>/dev/null || echo 0.0.0)"
if [ "$(printf '%s\n%s\n' "$cur" "$target" | sort -V | tail -1)" = "$cur" ] && [ "$cur" != "$target" ]; then
  target="$cur"
fi

# Already released? (tag exists, or already a CHANGELOG section)
if git rev-parse "v$target" >/dev/null 2>&1 || grep -qE "^## ${target//./\\.}( |\$)" CHANGELOG.md 2>/dev/null; then
  echo "none"; exit 0
fi

# --- build detailed release notes from commit subjects AND bodies ----------
# The detail lives in the commit bodies (the "why"/"how" paragraphs), so include
# them - wrapped + indented - under each entry, grouped Features / Fixes /
# Other, with a leading Breaking-changes section. Generated by an embedded
# Python pass (robust subject+body parsing beats sed/awk here).
export TARGET="$target" LAST_TAG="$last_tag" RANGE="$range"
export REL_DATE="$(date -u +%Y-%m-%d)"
python3 - <<'PYEOF'
import os, re, subprocess, textwrap

target, last_tag = os.environ["TARGET"], os.environ["LAST_TAG"]
rng, date = os.environ["RANGE"], os.environ["REL_DATE"]

raw = subprocess.run(
    ["git", "log", "--no-merges", "--pretty=format:%h%x1f%s%x1f%b%x1e", rng],
    capture_output=True, text=True).stdout

TYPE_RE = re.compile(r'^(?P<type>[a-z]+)(?:\((?P<scope>[^)]+)\))?(?P<bang>!)?:\s*(?P<desc>.+)$')
TRAILER_RE = re.compile(
    r'^(co-authored-by|signed-off-by|reviewed-by|acked-by|breaking[ -]change)\s*:',
    re.I)

feats, fixes, other, breaking = [], [], [], []
n_user = 0

def clean_body(body):
    """Split a commit body into blocks: ('p', text) paragraphs and ('li', text)
    list items, dropping trailers + [skip ci]. Blank lines break paragraphs;
    in-body bullets ('- '/'* '/'1. ') are preserved as list items, and their
    wrapped continuation lines are folded back into the item."""
    blocks, para, li = [], [], None

    def flush_para():
        if para:
            blocks.append(("p", " ".join(para))); para.clear()

    def flush_li():
        nonlocal li
        if li is not None:
            blocks.append(("li", " ".join(li))); li = None

    for ln in body.splitlines():
        s = ln.strip()
        if s == "":
            flush_para(); flush_li(); continue
        if TRAILER_RE.match(s) or "[skip ci]" in s:
            continue
        if re.match(r'^([-*]\s+|\d+[.)]\s+)', s):
            flush_para(); flush_li()
            li = [re.sub(r'^([-*]\s+|\d+[.)]\s+)', '', s)]
        elif li is not None:
            li.append(s)            # continuation line of the current list item
        else:
            para.append(s)
    flush_para(); flush_li()
    return blocks

for rec in (r for r in raw.split("\x1e") if r.strip()):
    parts = rec.strip("\n").split("\x1f")
    if len(parts) < 2:
        continue
    h, subj = parts[0].strip(), parts[1].strip()
    body = parts[2] if len(parts) > 2 else ""
    if subj.startswith("release:"):
        continue
    m = TYPE_RE.match(subj)
    if not m:
        other.append((h, None, subj, [])); n_user += 1; continue
    t, scope, bang, desc = (m.group("type"), m.group("scope"),
                            m.group("bang"), m.group("desc"))
    entry = (h, scope, desc, clean_body(body))
    n_user += 1
    if bang or re.search(r'^BREAKING[ -]CHANGE', body, re.M):
        breaking.append(entry)
    if t == "feat":
        feats.append(entry)
    elif t in ("fix", "perf", "refactor", "build", "revert"):
        fixes.append(entry)
    else:
        other.append(entry)

def render(entries, with_body=True):
    lines = []
    for h, scope, desc, blocks in entries:
        head = f"- **{scope}:** {desc}" if scope else f"- {desc}"
        lines.append(f"{head} (`{h}`)")
        if with_body:
            for kind, text in blocks:
                if kind == "li":
                    lines.append(textwrap.fill(text, width=98,
                                               initial_indent="  - ", subsequent_indent="    "))
                else:
                    lines.append(textwrap.fill(text, width=100,
                                               initial_indent="  ", subsequent_indent="  "))
    return "\n".join(lines)

def sections(level):
    h = "#" * level
    out = []
    for title, entries, body in (("Breaking changes", breaking, True),
                                 ("Features", feats, True),
                                 ("Fixes & improvements", fixes, True),
                                 ("Other changes", other, False)):
        if entries:
            out.append(f"{h} {title}\n\n{render(entries, body)}\n")
    return "\n".join(out)

since = f"since {last_tag}" if last_tag != "v0.0.0" else "in the initial release"
summary = (f"_Released {date}. {n_user} change" + ("s" if n_user != 1 else "")
           + f" {since}._")

# CHANGELOG.md block (## version, ### sections), prepended before the first "## ".
block = f"## {target} — {date}\n\n{summary}\n\n{sections(3)}".rstrip() + "\n"
cl = open("CHANGELOG.md").read().splitlines(keepends=True) if os.path.exists("CHANGELOG.md") else []
idx = next((i for i, l in enumerate(cl) if l.startswith("## ")), len(cl))
open("CHANGELOG.md", "w").write("".join(cl[:idx]) + block + "\n" + "".join(cl[idx:]))

# Per-release notes file (# title, ## sections).
notes = f"# CSR Dashboard v{target}\n\n{summary}\n\n{sections(2)}".rstrip() + "\n"
open(f"RELEASE-NOTES-v{target}.md", "w").write(notes)
PYEOF

echo "$target" > VERSION
echo "$target"
